### ISSUE TITLE
Scan Remediation: csi-plugin-provisioner.yaml.j2

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#12] opened 2020-01-15 15:59 UTC
## Template
`roles/csi-scale/templates/csi-plugin-provisioner.yaml.j2`

## Raw Scan
```
[REVIEW] scanned-statefulset-ibm-spectrum-scale-csi-driver-csi-scale-operator-attacher.yaml: spec.template.spec.containers[0].readinessProbe not defined (ContainerWithNoMatchingServiceHasReadinessProbe)
[REVIEW] scanned-statefulset-ibm-spectrum-scale-csi-driver-csi-scale-operator-provisioner.yaml: spec.template.spec.containers[0].readinessProbe not defined (ContainerWithNoMatchingServiceHasReadinessProbe)

[ERROR] scanned-statefulset-ibm-spectrum-scale-csi-driver-csi-scale-operator-provisioner.yaml: "ALL" not found in spec.template.spec.containers[0].securityContext.capabilities.drop (ContainerHasDropAll)
[ERROR] scanned-statefulset-ibm-spectrum-scale-csi-driver-csi-scale-operator-provisioner.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels (RequiredMetadataLabelsDefined)
[ERROR] scanned-statefulset-ibm-spectrum-scale-csi-driver-csi-scale-operator-provisioner.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under spec.template.metadata.labels (RequiredMetadataLabelsDefined)
[ERROR] scanned-statefulset-ibm-spectrum-scale-csi-driver-csi-scale-operator-provisioner.yaml: metering annotations ["productID" "productName" "productVersion"] not found under spec.template.metadata.annotations (MeteringAnnotationsDefined)
[ERROR] scanned-statefulset-ibm-spectrum-scale-csi-driver-csi-scale-operator-provisioner.yaml: neither spec.template.spec.containers[0].resources.limits.cpu nor spec.template.spec.containers[0].resources.requests.cpu is defined (ContainerDefinesResources)
[ERROR] scanned-statefulset-ibm-spectrum-scale-csi-driver-csi-scale-operator-provisioner.yaml: spec.template.spec.containers[0].livenessProbe not defined (ContainerHasLivenessProbe)
[ERROR] scanned-statefulset-ibm-spectrum-scale-csi-driver-csi-scale-operator-provisioner.yaml: spec.template.spec.containers[0].resources.limits.memory not defined (ContainerDefinesResources)
[ERROR] scanned-statefulset-ibm-spectrum-scale-csi-driver-csi-scale-operator-provisioner.yaml: spec.template.spec.containers[0].resources.requests.memory not defined (ContainerDefinesResources)
[ERROR] scanned-statefulset-ibm-spectrum-scale-csi-driver-csi-scale-operator-provisioner.yaml: use of hostPath at spec.template.spec.volumes[0].hostPath not allowed (NoHostPath)
[ERROR] scanned-statefulset-ibm-spectrum-scale-csi-driver-csi-scale-operator-provisioner.yaml: value "beta.kubernetes.io/arch" at some spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[i].matchExpressions[j].key not defined for architecture-based node affinity (PodHasArchBasedNodeAffinity)

```

## Action Items

- [ ]  "ALL" not found in spec.template.spec.containers[0].securityContext.capabilities.drop (ContainerHasDropAll)
- [x]  ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels 
- [x]  ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under spec.template.metadata.labels 
- [x]  metering annotations ["productID" "productName" "productVersion"] not found under spec.template.metadata.annotations (MeteringAnnotationsDefined)
- [ ]  neither spec.template.spec.containers[0].resources.limits.cpu nor spec.template.spec.containers[0].resources.requests.cpu is defined 
- [ ]  spec.template.spec.containers[0].livenessProbe not defined (ContainerHasLivenessProbe)
- [ ]  spec.template.spec.containers[0].resources.limits.memory not defined (ContainerDefinesResources)
- [ ]  spec.template.spec.containers[0].resources.requests.memory not defined (ContainerDefinesResources)
- [ ]  use of hostPath at spec.template.spec.volumes[0].hostPath not allowed (NoHostPath)
- [ ]  value "beta.kubernetes.io/arch" at some spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[i].matchExpressions[j].key not defined for architecture-based node affinity (PodHasArchBasedNodeAffinity)

**Comment by smitaraut** [comment] 2020-05-21 09:41
Is this still valid?

**Comment by mew2057** [comment] 2020-05-21 13:41
Technically yes, we still need a liveness probe and resource management, but apparently the rest were less of an issue.

**Comment by aspalazz** [comment] 2020-06-09 23:46
@mew2057 This is still set for CSI 2.0.0 - should we move it out?

**Comment by deeghuge** [comment] 2021-11-29 17:46
Duplicate of issue #467

**Closed by deeghuge** 2021-11-29 17:46 UTC
Labels: Component: Certification, Component: Templates, Environment: Kubernetes, Environment: OpenShift, Phase: Development, Severity: 2, Type: Bug, Type: Enhancement, Customer Probability: Can't Happen, Customer Impact: Minor
