### ISSUE TITLE
Random and Intermittent Pods Stuck in ContainerCreating Due to Volumes Not Mounting

### ISSUE THREAD

**Issue by tristan-le** [IBM/ibm-spectrum-scale-csi#214] opened 2020-05-29 16:16 UTC
**Bug Description**
We launched a system stress test for lightweight provisioning on a **Kubernetes** cluster that has 7 worker nodes.

Each deployment launches 1 pod that has 31 pvcs. The pods run a very simple busybox read/write of a 1 meg file.

After 357 total deployments (1 pod each), we see a random set of pods that are in ContainerCreating. They are distributed among all worker nodes. The number of pods with ContainerCreating appears to be decrementing over an extended period of time. 

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/66130947/83279820-8ceb2180-a18a-11ea-8df0-015e6ef0c97a.png">

Worker nodes have the following CPU and memory utilization:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/66130947/83282108-f9b3eb00-a18d-11ea-8273-b9331cd08eba.png">

The problem does not appear to be stress related.

Deleting the pod results in redeployment, but it is also stuck in ContainerCreating.

Description of pods show the following errors:
<img width="1546" alt="Screen Shot 2020-05-29 at 8 53 07 AM" src="https://user-images.githubusercontent.com/66130947/83279371-de46e100-a189-11ea-99e0-c5e92d9741ba.png">

What could be causing this?

This stress test is required for CSI 2.0.0.

**To Reproduce**
A stress test of multiple pods each with 31 lightweight pvc should demonstrate this. It is uncertain if other fileset pvc would result in the same thing.

**Expected behavior**
There should not be any pods stuck in ContainerCreating. If so, a deletion of the pod should cause the deployment to launch one that can run.

**Environment**
CSI 2.0.0 (Downloaded 5/21/20)

<img width="1544" alt="image" src="https://user-images.githubusercontent.com/66130947/83282652-c32aa000-a18e-11ea-8703-f88e4b30e5e3.png">

**Additional context**
A snap of the logs is resident on the system (Archie):
/ibm/fs0/CSI/CSI-2.0.0-tools/ibm-spectrum-scale-csi/tools/ibm-spectrum-scale-csi-logs_05-29-2020-08:17:17

**Comment by deeghuge** [comment] 2020-05-31 05:32
Hi @tristan-le ,
I see following in the logs 
`ibm-spectrum-scale-csi-vgccn.log:E0529 15:18:00.198231       1 utils.go:55] GRPC error: rpc error: code = Internal desc = ControllerPublishVolume : SKIP_MOUNT_UNMOUNT == yes and either fs0 or fs0 is not mounted on node archieprt05.`

So I checked the node mapping, I don't see node mapping for archieprt05 and all the pods you are mentioning are being scheduled on this node itself and CSI Driver is not able to figure out the mount status of fs0 hence the attach is failing. 

`  nodeMapping:
  - k8sNode: archieprt01
    spectrumscaleNode: archieprt01-40
  - k8sNode: archieprt02
    spectrumscaleNode: archieprt02-40
  - k8sNode: archieprt03
    spectrumscaleNode: archieprt03-40
  - k8sNode: archieprt04
    spectrumscaleNode: archieprt04-40
  - k8sNode: archieprt06
    spectrumscaleNode: archieprt06-40
  - k8sNode: archieprt07
    spectrumscaleNode: archieprt07-40
  - k8sNode: archieprt09
    spectrumscaleNode: archieprt09-40
  scaleHostpath: /ibm/fs0`

**Comment by MonicaLemay** [comment] 2020-06-01 13:36
I will remedy node mapping for Archie prt05.  I  will double check, but I think that there are other nodes that were mapped that had the same problem.

**Comment by MonicaLemay** [comment] 2020-06-01 13:49
Changed the cr file and applyied it:
# kubectl apply -f csiscaleoperators.csi.ibm.com.cr.yaml
csiscaleoperator.csi.ibm.com/ibm-spectrum-scale-csi configured
[root@archieprt01 CSI-2.0.0-210520] 2020-06-01 06:38:45
# date
Mon Jun  1 06:38:48 MST 2020
It looks like only the pods on archiepr05 are the ones still stuck in Container Creating.  We will close this defect later today if we can't recreate.  But I agree that it looks like a miss in the cr yaml

**Comment by MonicaLemay** [comment] 2020-06-01 14:16
It looks like even though, I fixed the custume resource file, the pods starting on archieprt05 are still stuck in ContainerCreating with the same error.  Do I have to delete the csi driver or anything else to get the volumes to mount?

**Comment by deeghuge** [comment] 2020-06-01 14:34
The POD are still in ContainerCreating because CSI Driver pod is not yet ready. 
[root@archieprt01 ~]# kubectl get pod -n ibm-spectrum-scale-csi-driver

NAME                                               READY   STATUS              RESTARTS   AGE
ibm-spectrum-scale-csi-6r2q7                       2/2     Running             0          38m
ibm-spectrum-scale-csi-9dbsf                       2/2     Running             0          38m
ibm-spectrum-scale-csi-attacher-0                  1/1     Running             0          27m
ibm-spectrum-scale-csi-d8zkt                       2/2     Running             0          38m
ibm-spectrum-scale-csi-nbh2r                       2/2     Running             0          38m
ibm-spectrum-scale-csi-operator-74564b7cd9-nxrln   1/1     Running             0          10d
ibm-spectrum-scale-csi-p69cp                       0/2     Terminating         0          10d
ibm-spectrum-scale-csi-provisioner-0               1/1     Running             0          32m
ibm-spectrum-scale-csi-rgvbq                       2/2     Running             0          38m
ibm-spectrum-scale-csi-v2fdt                       2/2     Running             0          38m
ibm-spectrum-scale-csi-vwsqz                       0/2     ContainerCreating   0          38m

Can you please check if there is issue with archieprt05  from Kubernetes side

**Comment by MonicaLemay** [comment] 2020-06-01 18:00
I have the csi pod correctly running.  I had to reboot archieprt05.  When I rebooted archieprt05, all of the pods that were assignted to archieprt05 moved to other nodes.  Those pods are still stuck in ContainerCreating for the same reason.  I deleted one of those pods so that the deployment would re-launch the pod.  It still has the same problem.

This shows that all nodes have CSI  driver running
 [root@archieprt01 ~] 2020-06-01 10:42:37
# kubectl get pods -A -o wide | grep csi
ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi-6r2q7                       2/2     Running             0          3h49m   9.11.139.26      archieprt06   <none>           <none>
ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi-9dbsf                       2/2     Running             0          3h49m   9.11.139.27      archieprt07   <none>           <none>
ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi-attacher-0                  1/1     Running             0          3h38m   10.244.250.11    archieprt02   <none>           <none>
ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi-d8zkt                       2/2     Running             0          3h49m   9.11.139.24      archieprt04   <none>           <none>
ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi-nbh2r                       2/2     Running             0          3h49m   9.11.139.23      archieprt03   <none>           <none>
ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi-operator-74564b7cd9-nxrln   1/1     Running             0          10d     10.244.250.10    archieprt02   <none>           <none>
ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi-provisioner-0               1/1     Running             0          3h44m   10.244.108.134   archieprt03   <none>           <none>
ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi-rgvbq                       2/2     Running             0          3h49m   9.11.139.22      archieprt02   <none>           <none>
ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi-v2fdt                       2/2     Running             0          3h49m   9.11.139.29      archieprt09   <none>           <none>
ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi-vwsqz                       2/2     Running             0          3h49m   9.11.139.25      archieprt05   <none>           <none>
[root@archieprt01 ~] 2020-06-01 10:42:59
# kubectl get pods -A -o wide | grep -vi Running | wc -l
30

This shows the deletion of a pod that is stuck in ContainerCreating.
kubectl delete pod -n test89-namespace                test89-busy-write-deployment1-66b85fc444-4vf45
pod "test89-busy-write-deployment1-66b85fc444-4vf45" deleted

The new pods is still stuck in Container Creating:
# kubectl describe pod -n test89-namespace     test89-busy-write-deployment1-66b85fc444-rnttd

What should a customer do if they encounter this type of situation?  Should they delete the deployements and pvc's and try again?  How does one recover from this?

**Comment by deeghuge** [comment] 2020-06-06 05:01
The pod mount will be very slow if they encounter such issue. it might take days to mount because for each attach retry time keep increasing exponentially. 
To fix the slowness and timeout of attach/detach one has to do following. 
`Set disable-attach-detach-reconcile-sync flag on the kube-controller-manager to true`

After setting to Archie, all pod come into running state without deleting them. 

CSI known issue : https://github.com/kubernetes/kubernetes/issues/84169

**Comment by MonicaLemay** [comment] 2020-06-06 14:50
Thanks Deepak.  How did you know to do this?  Is this knowledge that a good kubernetes admin would know?

**Comment by deeghuge** [comment] 2020-06-06 18:52
I was looking for error which you were facing and I came across issue having same details.

Frankly I am not sure about whether k8s admin will know such things in advance but I feel one with good Kubernetes admin knowledge will easily find out.

**Comment by MonicaLemay** [comment] 2020-06-06 19:58
Thanks Deepak.  How did you know to do this?  Is this knowledge that a good kubernetes admin would know?

**Comment by MonicaLemay** [comment] 2020-06-07 14:56
Thanks Deepak.  This answers my questions.  I read the kubernetes post 84169.  After they gave the workaround they said that the behaviour would be fixed in CSI v1.2.0.    Did we get that fix into our CSI 2.0.0?  Am I misunderstanding something?

**Comment by deeghuge** [comment] 2020-06-07 17:14
As per my understanding 84169 is still not completely fixed.  The issue is being fixed at various level(k8s,CSI Spec, External Attacher) so we need keep checking for all pieces to be checked in for complete fix. 

FYI : We are using CSI Spec 1.1.0 for 2.0.0.

**Comment by MonicaLemay** [comment] 2020-06-08 12:29
Great answer. Thanks

**Closed** 2020-06-08 16:56 UTC
Labels: Customer Impact: Localized high impact, Customer Probability: Medium, Environment: Kubernetes, Phase: Test, Severity: 2, Special Sev: Blocking, Type: Bug
