### ISSUE TITLE
Remove clusterID and FS uid from volumeHandle for static PVs

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#75] opened 2020-02-12 21:28 UTC
As for now, for static provisioning I need to provide for `volumeHandle` filesystem UID and cluster ID. Can you remove this requirement for PVs ? I would expect the path should be sufficient as the values are available in the GUI database.

```
volumeHandle: "clusterID;FSUID;path=/gpfs/fs1/staticdir"
```

**Comment by gandhisanjayv** [comment] 2020-02-12 22:21
helper script  is available to create pv yaml file. it needs to be run from worker node.
https://github.com/IBM/ibm-spectrum-scale-csi/blob/dev/tools/generate_pv_yaml.sh

**Comment by przem123** [comment] 2020-02-13 12:12
I have multiple directories needed for the static provisioning. I cannot run a script for this all the time. Please remove these two params so that I can create yaml files more efficient.

**Comment by przem123** [comment] 2020-02-14 11:40
Can you fix the issue ?

**Comment by deeghuge** [comment] 2020-07-28 11:48
This is working as per design. 
FSUID is required to check if filesystem is mount on that node. 
VolumeHandle is kept same so that volume handle for dynamic and static provisioning are in sync.

**Comment by deeghuge** [comment] 2020-12-18 09:28
Closing since this is working as designed and there is no plan to fix remove clusterID from volumeHandle for static pv

**Closed by deeghuge** 2020-12-18 09:28 UTC
Labels: Component: API, Phase: Field, Severity: 3, Target: Driver, Type: Enhancement, Type: Needs Design, Type: Working As Designed
