### ISSUE TITLE
CR enhancement to accept customized plugin registration path

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#308] opened 2020-09-11 05:18 UTC
**Describe the bug**
CR enhancement to accept customized plugin registration path

**To Reproduce**

Few k8s distribution uses a different default kubelet directory such as `/cm/local/apps/kubernetes/var/kubelet`, in such cases CSI driver fails with below error :

```
 Warning   FailedMount              pod/test2-79d5f946c4-2288v    MountVolume.MountDevice failed for volume "pvc-cb988ea5-d11e-41b0-96d8-9c70fec7fc81" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name spectrumscale.csi.ibm.com not found in the list of registered CSI drivers
```

We need to update the statefulsets and daemonset with this kubelet dirctory location for driver pods to be in running state .

**Expected behavior**
Need CR enhancement to accept customized plugin registration path

**Environment**
K8s/OCP

**Comment by madhuthorat** [comment] 2021-02-19 11:31
Tried to reproduce the issue using latest images CSI operator (based on v1.3) and CSI driver (dev test image for 2.2.0):
1. Changed root directory for kubelet service by updating /etc/sysconfig/kubelet to have:
--root-dir=/var/mykubelet

2. systemctl restart kubelet

3. Then installed CSI operator and CSI driver. The PODs came up and were running.

So not able to reproduce it so far. Will check with Abhishek on reproducing the issue.

**Comment by madhuthorat** [comment] 2021-02-22 14:54
Could reproduce this issue by making changes mentioned in previous comment on all the worker nodes.

**Comment by madhuthorat** [comment] 2021-02-25 03:25
Operator code changes are done. But recently found this CR would need some driver changes too, working on the same.

**Comment by madhuthorat** [comment] 2021-03-01 05:13
Submitted code for review with PR:
https://github.com/IBM/ibm-spectrum-scale-csi/pull/379

**Comment by madhuthorat** [comment] 2021-03-06 10:49
As the change affects CR, it has been suggested to have the changes tested before merging the changes. Yesterday have requested Abhishek, Chetan and Vrushal to test the change with the following images and other details:
1. Images are:
Driver image: quay.io/madhuthorat/ibm-spectrum-scale-csi-driver-dev:dr_issue308
Operator image: quay.io/madhuthorat/ibm-spectrum-scale-csi-operator-dev:op_issue308

2. Update above image in this yaml and then use: https://raw.githubusercontent.com/madhuthorat/ibm-spectrum-scale-csi/custom_kubdir26Feb/generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml

3. Also please use this updated CR with new variable "kubeletRootDirPath": https://raw.githubusercontent.com/madhuthorat/ibm-spectrum-scale-csi/custom_kubdir26Feb/operator/config/samples/csi_v1_csiscaleoperator.yaml

Tip for testing:
If one wants to change root directory path for kubelet service on their nodes, then please refer to the steps listed in one of the previous comments in this issue.

**Comment by Jainbrt** [comment] 2021-03-08 14:16
Thanks Madhu for the fix, we are working on validation for the same.

**Comment by madhuthorat** [comment] 2021-03-10 18:50
Thank you Abhishek and Vrushal for verifying the fix.

As the code has been merged then can we close this issue?

**Closed** 2021-03-11 08:40 UTC
Labels: Customer Impact: Localized high impact, Customer Impact: Minor, Special Sev: Must Fix, Type: Enhancement
