### ISSUE TITLE
cloned pvcs remain in pending state, if we reboot a node where mmxcp is running.

### ISSUE THREAD

**Issue by vrushch** [IBM/ibm-spectrum-scale-csi#534] opened 2021-11-26 09:00 UTC
**Describe the bug**
Created cloned pvc and rebooted node where mmxcp was running. cloned PVC is still in Pending state and CSI is 
retrying mmxcp continuously.

**To Reproduce**
1. Create SC and PVC
2. write data to pvc. ( added 788 mb data )
3. Create clone pvc with above pvc as source
4. Reboot spectrum scale node where mmxcp is running
5. clone pvc never go to Bound state

**Expected behavior**
Cloned PVC should go to Bound state. As this scenario can occur anytime due to multiple reasons on client environment. 

**Environment**
Please run the following an paste your output here:
``` bash


# Deployment
[root@remote-csi-master fileset]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32}
[root@remote-csi-master fileset]#


[root@remote-csi-scalegui ~]# rpm -qa | grep gpfs
gpfs.msg.en_US-5.1.2-1.noarch
gpfs.adv-5.1.2-1.x86_64
gpfs.gpl-5.1.2-1.noarch
gpfs.gui-5.1.2-1.noarch
gpfs.afm.cos-1.0.0-4.x86_64
gpfs.librdkafka-5.1.2-1.el7.x86_64
gpfs.gss.pmsensors-5.1.2-1.el7.x86_64
gpfs.java-5.1.2-1.x86_64
gpfs.base-5.1.2-1.x86_64
gpfs.license.adv-5.1.2-1.x86_64
gpfs.crypto-5.1.2-1.x86_64
gpfs.gskit-8.0.55-19.1.x86_64
gpfs.docs-5.1.2-1.noarch
gpfs.compression-5.1.2-1.x86_64
gpfs.gss.pmcollector-5.1.2-1.el7.x86_64
[root@remote-csi-scalegui ~]#
```

**Additional context**
```
[root@remote-csi-master ~]# kubectl get pvc
NAME                   STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                     AGE
clone-scale-fset-pvc   Pending                                                                        ibm-spectrum-scale-csi-fileset   21h
scale-fset-pvc         Bound     pvc-639b8cac-7e9a-44d6-86e7-b204d526c252   1Gi        RWX            ibm-spectrum-scale-csi-fileset   22h
[root@remote-csi-master ~]#
```

mmxcp is still there in CCR
```
[root@remote-csi-worker-1 ~]# /usr/lpp/mmfs/bin/mmccr fget _xcpRunning /tmp/2
[root@remote-csi-worker-1 ~]# cat /tmp/2
XCP1637859380879320589;%2Fibm%2Ffs1%2Fpvc%2D639b8cac%2D7e9a%2D44d6%2D86e7%2Db204d526c252%2Fpvc%2D639b8cac%2D7e9a%2D44d6%2D86e7%2Db204d526c252%2Ddata;%2Fibm%2Ffs1%2Fpvc%2Def889d8;
[root@remote-csi-worker-1 ~]#
```

CSI retrying mmxcp
```
[root@remote-csi-scalegui ~]# curl --insecure -u user:pass 1 -X GET https://localhost:443/scalemgmt/v2/jobs/

{
    "jobId" : 1000000000301,
    "status" : "FAILED",
    "submitted" : "2021-11-26 00:24:13,455",
    "completed" : "2021-11-26 00:25:29,020"
  }, {
    "jobId" : 1000000000302,
    "status" : "FAILED",
    "submitted" : "2021-11-26 00:30:31,836",
    "completed" : "2021-11-26 00:31:52,498"
  }, {
    "jobId" : 1000000000303,
    "status" : "FAILED",
    "submitted" : "2021-11-26 00:32:58,030",
    "completed" : "2021-11-26 00:34:13,183"
  }, {
    "jobId" : 1000000000304,
    "status" : "FAILED",
    "submitted" : "2021-11-26 00:37:06,244",
    "completed" : "2021-11-26 00:38:22,391"
  }, {
    "jobId" : 1000000000305,
    "status" : "FAILED",
    "submitted" : "2021-11-26 00:43:24,622",
    "completed" : "2021-11-26 00:44:40,940"
  }, {
    "jobId" : 1000000000306,
    "status" : "FAILED",
    "submitted" : "2021-11-26 00:47:58,040",
    "completed" : "2021-11-26 00:49:16,894"
  }, {
    "jobId" : 1000000000307,
    "status" : "FAILED",
    "submitted" : "2021-11-26 00:49:43,102",
    "completed" : "2021-11-26 00:51:02,484"
  }
  ```
  
  There are over 200's of such failed jobs
  ```
  [root@remote-csi-scalegui ~]# curl --insecure -u user:pass -X GET https://localhost:443/scalemgmt/v2/jobs/1000000000307
{
  "jobs" : [ {
    "jobId" : 1000000000307,
    "status" : "FAILED",
    "submitted" : "2021-11-26 00:49:43,102",
    "completed" : "2021-11-26 00:51:02,484",
    "runtime" : 79382,
    "request" : {
      "type" : "PUT",
      "url" : "/scalemgmt/v2/filesystems/fs1/filesets/pvc-639b8cac-7e9a-44d6-86e7-b204d526c252/directoryCopy/pvc-639b8cac-7e9a-44d6-86e7-b204d526c252-data"
    },
    "result" : {
      "progress" : [ ],
      "commands" : [ "mmxcp enable --source '/ibm/fs1/pvc-639b8cac-7e9a-44d6-86e7-b204d526c252/pvc-639b8cac-7e9a-44d6-86e7-b204d526c252-data' --target '/ibm/fs1/pvc-ef889d80-80b,
      "stdout" : [ ],
      "stderr" : [ "EFSSG0632C Command execution aborted." ],
      "exitCode" : 8
    },
    "pids" : [ ]
  } ],
  "status" : {
    "code" : 200,
    "message" : "The request finished successfully."
  }
}[root@remote-csi-scalegui ~]#
```
Running mmxcp command and I rebooted worker-1 node
```
[root@remote-csi-worker-1 ~]#  /usr/lpp/mmfs/bin/mmxcp list all
PARALLEL_COPY_ID:XCP1637839080847313075
  PARALLEL_COPY_SOURCE_PATH:/ibm/fs1/pvc-639b8cac-7e9a-44d6-86e7-b204d526c252/pvc-639b8cac-7e9a-44d6-86e7-b204d526c252-data
  PARALLEL_COPY_TARGET_PATH:/ibm/fs1/pvc-ef889d80-80b8-4ed2-a5b7-5e1af9529ac7/pvc-ef889d80-80b8-4ed2-a5b7-5e1af9529ac7-data
  PARALLEL_COPY_SOURCE_DEVICE:fs1
  PARALLEL_COPY_TARGET_DEVICE:fs1
  PARALLEL_COPY_NODE_LIST:10.11.102.143,10.11.102.71,10.11.99.68
  PARALLEL_COPY_START_TIME:Thu Nov 25 03-18-00 2021
[root@remote-csi-worker-1 ~]#
```

**Comment by madhuthorat** [comment] 2021-11-26 13:57
Checked the CSI logs. Found mmxcp returning EFSSG0632C. There is special handling of error "EFSSG0632C = Command execution aborted" in volume cloning code (similar to snapshots code) in CSI code, where we don't return the error to Kubernetes, so next time when the same request comes, CSI driver re-attempts to use the same REST API again, but mmxcp returns the same error again. This error is returned by mmxcp even after node reboot has completed.
_if strings.Contains(err.Error(), "EFSSG0632C") {
			// EFSSG0632C = Command execution aborted
			// Store VOLCOPY_JOB_NOT_STARTED in volcopyjobstatusmap if error was due to same mmxcp in progress
			// or max no. of mmxcp already running. In these cases we want to retry again
			// in the next k8s rety cycle
			jobDetails.jobStatus = VOLCOPY_JOB_NOT_STARTED
}_

Have sent an email to DPE team to understand how to handle this error.

**Comment by deeghuge** [comment] 2021-11-30 07:03
Duplicate of #402

**Comment by Jainbrt** [comment] 2022-09-10 04:22
this should be fixed as a part of #402

**Closed by Jainbrt** 2022-09-10 04:22 UTC
Labels: Type: Bug, Customer Probability: Low, Customer Impact: Localized high impact, Component: Clone
