### ISSUE TITLE
CSI upgrade from 2.4.0 to 2.5.0 fails

### ISSUE THREAD

**Issue by amdabhad** [IBM/ibm-spectrum-scale-csi#730] opened 2022-05-24 10:03 UTC
- Initial version of CSI on the cluster: 1.1.0
- Upgrade till 2.4.0 was successful
- Cluster details: OpenShift x86, RHEL 7.9 worker nodes with GPFS 5.1.1.2. This is standalone CSI (without CNSA)
- Error seen while upgrading:
```
# oc apply -f ibm-spectrum-scale-csi-operator.yaml
clusterrole.rbac.authorization.k8s.io/ibm-spectrum-scale-csi-operator configured
clusterrolebinding.rbac.authorization.k8s.io/ibm-spectrum-scale-csi-operator unchanged
serviceaccount/ibm-spectrum-scale-csi-operator configured
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration"
...
to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "ibm-spectrum-scale-csi-operator", Namespace: "ibm-spectrum-scale-csi-driver"
for: "ibm-spectrum-scale-csi-operator.yaml": Deployment.apps "ibm-spectrum-scale-csi-operator" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: "runner"
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"controller-gen.kubebuilder.io/version":"v0.4.1",
...
to:
Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "csiscaleoperators.csi.ibm.com", Namespace: ""
for: "ibm-spectrum-scale-csi-operator.yaml": CustomResourceDefinition.apiextensions.k8s.io "csiscaleoperators.csi.ibm.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema

```
- RTC issue: 295320

**Comment by nitishkumar4** [comment] 2022-06-16 05:53
For Kubernetes: 1.13+
# kubectl api-resources | grep  customresourcedefinitions
customresourcedefinitions             crd,crds              apiextensions.k8s.io/v1                       false        CustomResourceDefinition

**Comment by nitishkumar4** [comment] 2022-06-20 05:03
### Steps to reproduce the issue

### Environment
```
# oc version
Client Version: 4.7.45
Server Version: 4.7.45
Kubernetes Version: v1.20.14+0d60930
```

> Note: If users are using k8s 1.22+ then they won't be able to install CSI version 2.2.0 or below as apiextensions.k8s.io/v1beta1 for CRD is fully deprecated & unavailable from k8s 1.22


Installing CSI v2.1.0
===
```
# kubectl create -f https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi/v2.1.0/generated/installer/ibm-spectrum-scale-csi-operator.yaml
...
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/csiscaleoperators.csi.ibm.com created
```
```
# kubectl  get crd csiscaleoperators.csi.ibm.com -o yaml | grep " preserveUnknownFields:"
  preserveUnknownFields: true
```

Uprading from CSI v2.1.0 to CSI v2.2.0
===
```
kubectl apply -f https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi/v2.2.0/generated/installer/ibm-spectrum-scale-csi-operator.yaml
...
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Warning: resource customresourcedefinitions/csiscaleoperators.csi.ibm.com is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/csiscaleoperators.csi.ibm.com configured
```
```
kubectl get crd csiscaleoperators.csi.ibm.com -o yaml | grep " preserveUnknownFields:"
  preserveUnknownFields: true
```

Upgrading from CSI v2.2.0 to CSI v2.3.0
===
```
kubectl apply -f https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi/v2.3.0/generated/installer/ibm-spectrum-scale-csi-operator.yaml
customresourcedefinition.apiextensions.k8s.io/csiscaleoperators.csi.ibm.com configured
```
```
kubectl get crd csiscaleoperators.csi.ibm.com -o yaml | grep " preserveUnknownFields:"
  preserveUnknownFields: true
```

Upgrading from CSI v2.3.0 to CSI v2.4.0
===
```
kubectl apply -f https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi/v2.4.0/generated/installer/ibm-spectrum-scale-csi-operator.yaml
customresourcedefinition.apiextensions.k8s.io/csiscaleoperators.csi.ibm.com configured
```
```
kubectl get crd csiscaleoperators.csi.ibm.com -o yaml | grep " preserveUnknownFields:"
  preserveUnknownFields: true
```
Upgrading from CSI v2.4.0 to CSI v2.5.0
===
```
kubectl apply -f https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi/v2.5.0/generated/installer/ibm-spectrum-scale-csi-operator.yaml
...
The CustomResourceDefinition "csiscaleoperators.csi.ibm.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
```

**Comment by nitishkumar4** [comment] 2022-06-20 05:10
Root Cause Analysis
===

If upgrading from CSI 2.2.0 and prior version.
CRD uses API version v1beta1,
v1beta1 has field spec.preserveUnknownFields: true
v1beta1 doesnot support CRD fields with default values.


During upgrade from v1beta1 to v1, i.e: CSI v2.2.0 to CSI v2.3.0. 
CRD gets upgraded but preserveUnknownFields stays as true.
Since CRD till v2.4.0 doesn't contain any default values for fields. No error occurs.

In CSI 2.5.0 CRD uses default values for certain fields, like `spec.attacherNodeSelector`.
Even though v1 API supports default values, applying CRD fails.
This is because `spec.preserveUnknownFields` is set as true(coming from upgrade)
In v1 API preserveUnknownFields should be false to support default values.


This error doesnot occur when upgrading from 2.3.0 and above, becasue
preserveUnknownField is already set as undefined by default in v1 API.

**Comment by nitishkumar4** [comment] 2022-06-20 05:34
Solution
===

#### Manual workaround

- If someone is using CSI version 2.3.0+ and have a history of upgrade from CSI 2.2.0 and prior version. Then before upgrading to CSI v2.5.0 they must set `preserveUnknownFields` as false or undefined in the csiscaleoperator CRD. 

```
kubectl patch crd csiscaleoperators.csi.ibm.com -p '{"spec":{"preserveUnknownFields":false}}'
```

**Comment by nitishkumar4** [comment] 2022-07-05 06:16
In upgrade page documentation of 2.5.0 , 2.6.0, 2.7.0+ before applying the operator manifest, one must ensure that CSI CR is allowed to use default values. For this existing CRD must be patched. 

Doc Link:  https://www.ibm.com/docs/en/spectrum-scale-csi?topic=upgrading-spectrum-scale-csi-25-26 

2. CSIScaleOperator custom resource should be allowed to use default values.
To ensure this, set CustomResourceDefination field `spec.preserveUnknowFields` as `false`.

kubectl patch crd csiscaleoperators.csi.ibm.com -p '{"spec":{"preserveUnknownFields":false}}'

**Comment by Jainbrt** [comment] 2022-07-05 06:20
@nitishkumar4 I think good idea is to add namespace to the command

**Comment by nitishkumar4** [comment] 2022-07-05 06:43
@Jainbrt  This is a patch for CRD, CRD is cluster-scoped resource. So it should be fine.

**Comment by deeghuge** [comment] 2022-08-08 09:19
@Jainbrt @nitishkumar4 can we close this ?

**Closed by deeghuge** 2022-08-08 09:19 UTC
Labels: Severity: 2, Type: Bug, Customer Probability: High, Customer Impact: Localized low impact, Found In: 2.5.0
