### ISSUE TITLE
Add "used space" info to Scale CSI driver

### ISSUE THREAD

**Issue by debu66er** [IBM/ibm-spectrum-scale-csi#633] opened 2022-02-22 08:44 UTC
It seems current Scale CSI implementation doesn't implement used space functionality from CSI spec.

OpenShift administrators are used to check such info at PVC level from the web console or tune their own Grafana dashboards to monitor such information (this is possible since OpenShift 4.3: https://access.redhat.com/solutions/3020851).

**Comment by deeghuge** [comment] 2022-06-30 04:37
Duplicate of #489

**Closed** 2022-06-30 04:39 UTC
Labels: Type: Enhancement
