### ISSUE TITLE
Sidecar pod has crash loopback with CSI2.10 GA Version

### ISSUE THREAD

**Issue by ps20renar** [IBM/ibm-spectrum-scale-csi#1076] opened 2023-12-21 12:06 UTC
## Describe the bug
We see after the update of CNSA5.1.9.1 in CSI 2.10 CrashLoopBackOff on a OCP-Cluster with RHACS active

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. OCP 4.12.18
2. CNSA 5.1.9.1
3. CSI2.10

### Data Collection and Debugging

Environmental output

$ oc get pods -n ibm-spectrum-scale-csi
NAME                                                  READY   STATUS             RESTARTS           AGE
ibm-spectrum-scale-csi-2ktdm                          3/3     Running            0                  14h
ibm-spectrum-scale-csi-5tftj                          3/3     Running            0                  6d14h
ibm-spectrum-scale-csi-attacher-7948fc5bc5-42768      0/1     CrashLoopBackOff   335 (3m21s ago)    15h
ibm-spectrum-scale-csi-attacher-7948fc5bc5-c6w6t      0/1     CrashLoopBackOff   3329 (3m49s ago)   6d14h
ibm-spectrum-scale-csi-jdtzm                          3/3     Running            0                  6d14h
ibm-spectrum-scale-csi-jm2zj                          3/3     Running            0                  16h
ibm-spectrum-scale-csi-operator-7586958d94-pnc9z      1/1     Running            0                  16h
ibm-spectrum-scale-csi-provisioner-8766dd855-d9c5k    0/1     CrashLoopBackOff   343 (105s ago)     16h
ibm-spectrum-scale-csi-qxwfr                          3/3     Running            0                  15h
ibm-spectrum-scale-csi-resizer-58f4b68bf9-fjffc       0/1     CrashLoopBackOff   343 (3m25s ago)    16h
ibm-spectrum-scale-csi-snapshotter-7664cdd87b-cmcxn   0/1     CrashLoopBackOff   343 (105s ago)     16h
ibm-spectrum-scale-csi-wvqrp                          3/3     Running            0                  6d14h

$ oc logs -p ibm-spectrum-scale-csi-attacher-7948fc5bc5-42768
I1221 06:54:38.628462       1 main.go:96] Version: v4.3.0
I1221 06:54:38.629666       1 connection.go:164] Connecting to unix:///var/lib/kubelet/plugins/spectrumscale.csi.ibm.com/csi.sock
W1221 06:54:48.630447       1 connection.go:183] Still connecting to unix:///var/lib/kubelet/plugins/spectrumscale.csi.ibm.com/csi.sock

Tool to collect the CSI snap:

Please see TS015037162
### Add labels

- Component:
- Severity:
- Customer Impact:
- Customer Probability:
- Phase:

Note : See [labels](https://github.com/IBM/ibm-spectrum-scale-csi/labels) for the labels

**Comment by ps20renar** [comment] 2024-01-09 07:53
We found the issue, the reason for this was Dynatrace. Here are the article from redhead: https://access.redhat.com/solutions/6937681

**Comment by badri-pathak** [comment] 2024-01-11 06:23
Resolution Summary:

Restricted-csi SCC being applied to system pods causing them to crash

https://access.redhat.com/solutions/6937681


Root Cause

The restricted-csi SCC is not a default SCC, but is instead added by the Dynatrace utility. See the Dynatrace documentation

SCCs are defined at the global scope and are associated with individual users and groups within the cluster.

When a Pod is create without an SCC definition, it is assigned an SCC based on the current context for the

creation and the privileges of the associated ServiceAccount/User creating the Pod.

Solution: --> they deleted the scc

The pods must be configured **spectrum-scale-csiaccess** scc
_[openshift.io/scc](http://openshift.io/scc): spectrum-scale-csiaccess_

**Comment by badri-pathak** [comment] 2024-01-11 06:24
The issue can be closed as the installation was succeeded.

**Comment by ps20renar** [comment] 2024-01-18 21:30
closed

**Closed** 2024-01-29 21:44 UTC
Labels: Type: Bug
