### ISSUE TITLE
csi driver not terminating when requested to delete 

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-csi#92] opened 2019-11-22 16:35 UTC
After running for some time with operator and driver, I attempted to remove the driver... but mistakenly removed the operator as described here: https://github.com/IBM/ibm-spectrum-scale-csi-operator/issues/68

However, it seems  I'm unable to successfully remove the driver with the same yaml file creating the driver...

```
[root@c943f4n01-pvt csi-operator-ansible]# ./operator-helper.sh get_pods
+ oc get pods -n ibm-spectrum-scale-csi-driver
NAME                                               READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-attacher-0                  1/1     Running   0          42h
ibm-spectrum-scale-csi-operator-6ff9cf6979-k2gpd   2/2     Running   0          42h
ibm-spectrum-scale-csi-provisioner-0               1/1     Running   0          42h
ibm-spectrum-scale-csi-vk7kr                       2/2     Running   0          41m
ibm-spectrum-scale-csi-vpz6v                       2/2     Running   0          41m
ibm-spectrum-scale-csi-ww78g                       2/2     Running   0          41m
+ set +x
[root@c943f4n01-pvt csi-operator-ansible]#
```

Then since, i've tried removing the driver multiple times:
```
[root@c943f4n01-pvt csi-operator-ansible]# ./operator-helper.sh removeDR
csiscaleoperator.scale.ibm.com "ibm-spectrum-scale-csi" deleted
```

But pods continue to run: 
```
[root@c943f4n01-pvt csi-operator-ansible]# ./operator-helper.sh get_pods
+ oc get pods -n ibm-spectrum-scale-csi-driver
NAME                                   READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-attacher-0      1/1     Running   0          42h
ibm-spectrum-scale-csi-provisioner-0   1/1     Running   0          42h
ibm-spectrum-scale-csi-vk7kr           2/2     Running   0          55m
ibm-spectrum-scale-csi-vpz6v           2/2     Running   0          55m
ibm-spectrum-scale-csi-ww78g           2/2     Running   0          55m
+ set +x
```

it's been around 14 minutes and no changes ... still "Running" 

Here's the versions of the images being deployed: 
```
[root@c943f4n01-pvt csi-operator-ansible]# ./operator-helper.sh version
--- POD: ibm-spectrum-scale-csi-attacher-0 ---
  ibm-spectrum-scale-csi-attacher:
    Container ID:  cri-o://6798f2aad5ddc2968368080b52e6d173e4ab6155e4a82b9da133d23c3774dee6
    Image:         quay.io/k8scsi/csi-attacher:v1.0.0
    Image ID:      quay.io/k8scsi/csi-attacher@sha256:e57bb6abf0d78e638f70d38bdb07ee30ffe42d423a14fb2f910c11afab3a5e01
--- POD: ibm-spectrum-scale-csi-provisioner-0 ---
  csi-provisioner:
    Container ID:  cri-o://5334023271ac883db03e032ecf46439c9f98c992272a31a41df4c7edd6caef60
    Image:         quay.io/k8scsi/csi-provisioner:v1.0.0
    Image ID:      quay.io/k8scsi/csi-provisioner@sha256:cd0df00950e7b50154e83e29010eb2f2bfe0b661fb7fdd65c6621e8a49cd2bc0
--- POD: ibm-spectrum-scale-csi-vk7kr ---
  driver-registrar:
    Container ID:  cri-o://39e209f1237d2a3f6344905c3eb79b35b7674349d40872d992ca90f8d23770d7
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
    Image ID:      quay.io/k8scsi/csi-node-driver-registrar@sha256:5ad51d40e6de6762ae9bf2acbcf7117d46c87bc50048a337ce5a5cd6697498b4
--
  ibm-spectrum-scale-csi:
    Container ID:  cri-o://5773bf605f616207c5f8e5674d191ffb1b2fa50ced709dc1e2bd3424adab1893
    Image:         quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v0.9.1
    Image ID:      quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:e5926978bd4f4a553df18fc79ac532037c4e31e3a2cdaa6a5c06014fba02c808
--- POD: ibm-spectrum-scale-csi-vpz6v ---
  driver-registrar:
    Container ID:  cri-o://d71f2b8b96edd5e48cb56ec60843471675ac9efcc7b7615c9fa20baa34810e0e
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
    Image ID:      quay.io/k8scsi/csi-node-driver-registrar@sha256:5ad51d40e6de6762ae9bf2acbcf7117d46c87bc50048a337ce5a5cd6697498b4
--
  ibm-spectrum-scale-csi:
    Container ID:  cri-o://bded886e5b2e3aedc0b008bda5499c6572ee6e51681659c9ceb05d3cd2579432
    Image:         quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v0.9.1
    Image ID:      quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:e5926978bd4f4a553df18fc79ac532037c4e31e3a2cdaa6a5c06014fba02c808
--- POD: ibm-spectrum-scale-csi-ww78g ---
  driver-registrar:
    Container ID:  cri-o://e59f0ad8029ae46b4023e28e76226446335fefaccfa8a4cbf2b3265a7409f3a3
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
    Image ID:      quay.io/k8scsi/csi-node-driver-registrar@sha256:5ad51d40e6de6762ae9bf2acbcf7117d46c87bc50048a337ce5a5cd6697498b4
--
  ibm-spectrum-scale-csi:
    Container ID:  cri-o://bce2077dbcca30c17c782b1bb991b2bdef1d6cec645dc91c849eb6554008c689
    Image:         quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v0.9.1
    Image ID:      quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:e5926978bd4f4a553df18fc79ac532037c4e31e3a2cdaa6a5c06014fba02c808
```

**Comment by mew2057** [comment] 2020-02-20 20:38
At its core this issue  is that if the operator deployment is deleted without removing the Custom Resource.  I  think this is just a problem with the operator  in general. This  is borderline  wontfix I think.

**Comment by smitaraut** [comment] 2020-03-18 11:56
@mew2057 Why is this tagged as "Documentation"? What should we document?

**Comment by deeghuge** [comment] 2020-12-18 09:12
Closing since this is working as designed

**Closed by deeghuge** 2020-12-18 09:12 UTC
Labels: Phase: Test, Severity: 4, Target: Driver, Target: Operator, Type: Documentation, Type: Working As Designed
