### ISSUE TITLE
Lightweight mode does not enforce quota

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#101] opened 2020-02-19 18:34 UTC
I requested 1GB dynamic lightweight volume. Unfortunately, I can write unlimited amount of data:

```
sh-4.2$ ls -lh
total 2.0G
-rw-rw-rw-. 1 1000770000 root 1.0G Feb 19 18:28 file.txt
-rw-rw-rw-. 1 1000770000 root 1.0G Feb 19 18:28 file2.txt
```

Also, the `df` output on pods is incorrectly showing full filesystem size (15T):
```
sh-4.2$ df -hT
Filesystem             Type     Size  Used Avail Use% Mounted on
overlay                overlay  200G   81G  120G  41% /
tmpfs                  tmpfs     64M     0   64M   0% /dev
tmpfs                  tmpfs     63G     0   63G   0% /sys/fs/cgroup
shm                    tmpfs     64M     0   64M   0% /dev/shm
tmpfs                  tmpfs     63G  4.1G   59G   7% /etc/passwd
remote_fs0_1m          gpfs      15T   62G   15T   1% /ltfset
/dev/mapper/sr650-root xfs      200G   81G  120G  41% /etc/hosts
tmpfs                  tmpfs     63G   24K   63G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                  tmpfs     63G     0   63G   0% /proc/acpi
tmpfs                  tmpfs     63G     0   63G   0% /proc/scsi
tmpfs                  tmpfs     63G     0   63G   0% /sys/firmware
```

Can you fix these issues ?

**Comment by mew2057** [comment] 2020-02-20 20:40
FYI @deeghuge and @smitaraut this looks like a serious issue.

**Comment by gandhisanjayv** [comment] 2020-02-20 20:48
known limitation documented in KC
```
The known limitations are the following:

    IBM Spectrum Scale Container Storage Interface driver does not honor the size specified in PersistentVolumeClaim for lightweight volume.
```
https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_limitations.html

**Comment by smitaraut** [comment] 2020-02-21 05:34
The reason for this is that quota cannot be set on Spectrum Scale directories. If honoring the volume size is critical to you then you must use fileset based PVC. This is going to remain as permanent restriction.

**Comment by smitaraut** [comment] 2020-02-27 06:00
Closing this as working as designed

**Closed by smitaraut** 2020-02-27 06:00 UTC
Labels: Phase: Field, Severity: 3, Target: Driver, Type: Bug
