### ISSUE TITLE
Scan Remediation: csi-plugin.yaml.j2

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#13] opened 2020-01-15 15:56 UTC
## Template
`roles/csi-scale/templates/csi-plugin.yaml.j2`

## Raw Scan
```
[REVIEW] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: spec.template.spec.containers[0].readinessProbe not defined (ContainerWithNoMatchingServiceHasReadinessProbe)
[REVIEW] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: spec.template.spec.containers[1].readinessProbe not defined (ContainerWithNoMatchingServiceHasReadinessProbe)

[WARNING] scanned-serviceaccount-ibm-spectrum-scale-csi-driver-ibm-spectrum-scale-csi-operator.yaml: no imagePullSecrets defined, pods will not be able to pull namespace-scoped images from the local registry (ServiceAccountHasPullSecret)

[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: "ALL" not found in spec.template.spec.containers[0].securityContext.capabilities.drop (ContainerHasDropAll)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: "ALL" not found in spec.template.spec.containers[1].securityContext.capabilities.drop (ContainerHasDropAll)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels (RequiredMetadataLabelsDefined)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under spec.template.metadata.labels (RequiredMetadataLabelsDefined)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: metering annotations ["productID" "productName" "productVersion"] not found under spec.template.metadata.annotations (MeteringAnnotationsDefined)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: neither spec.template.spec.containers[0].resources.limits.cpu nor spec.template.spec.containers[0].resources.requests.cpu is defined (ContainerDefinesResources)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: neither spec.template.spec.containers[1].resources.limits.cpu nor spec.template.spec.containers[1].resources.requests.cpu is defined (ContainerDefinesResources)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: spec.template.spec.containers[0].livenessProbe not defined (ContainerHasLivenessProbe)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: spec.template.spec.containers[0].resources.limits.memory not defined (ContainerDefinesResources)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: spec.template.spec.containers[0].resources.requests.memory not defined (ContainerDefinesResources)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: spec.template.spec.containers[1].livenessProbe not defined (ContainerHasLivenessProbe)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: spec.template.spec.containers[1].resources.limits.memory not defined (ContainerDefinesResources)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: spec.template.spec.containers[1].resources.requests.memory not defined (ContainerDefinesResources)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: use of hostNetwork at spec.template.spec.hostNetwork not allowed (NoHostNetwork)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: use of hostPath at spec.template.spec.volumes[0].hostPath not allowed (NoHostPath)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: use of hostPath at spec.template.spec.volumes[1].hostPath not allowed (NoHostPath)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: use of hostPath at spec.template.spec.volumes[2].hostPath not allowed (NoHostPath)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: use of hostPath at spec.template.spec.volumes[3].hostPath not allowed (NoHostPath)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: use of hostPath at spec.template.spec.volumes[5].hostPath not allowed (NoHostPath)
[ERROR] scanned-daemonset-ibm-spectrum-scale-csi-driver-csi-scale-operator.yaml: value "beta.kubernetes.io/arch" at some spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[i].matchExpressions[j].key not defined for architecture-based node affinity (PodHasArchBasedNodeAffinity)

```

## Action Items

- [ ] "ALL" not found in spec.template.spec.containers[0].securityContext.capabilities.drop (ContainerHasDropAll)
- [ ] "ALL" not found in spec.template.spec.containers[1].securityContext.capabilities.drop (ContainerHasDropAll)
- [x] ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels (RequiredMetadataLabelsDefined)
- [x] ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under spec.template.metadata.labels 
- [x] metering annotations ["productID" "productName" "productVersion"] not found under spec.template.metadata.annotations (MeteringAnnotationsDefined)
- [ ] neither spec.template.spec.containers[0].resources.limits.cpu nor spec.template.spec.containers[0].resources.requests.cpu is defined (ContainerDefinesResources)
- [ ] neither spec.template.spec.containers[1].resources.limits.cpu nor spec.template.spec.containers[1].resources.requests.cpu is defined (ContainerDefinesResources)
- [ ] spec.template.spec.containers[0].livenessProbe not defined (ContainerHasLivenessProbe)
- [ ] spec.template.spec.containers[0].resources.limits.memory not defined (ContainerDefinesResources)
- [ ] spec.template.spec.containers[0].resources.requests.memory not defined (ContainerDefinesResources)
- [ ] spec.template.spec.containers[1].livenessProbe not defined (ContainerHasLivenessProbe)
- [ ] spec.template.spec.containers[1].resources.limits.memory not defined (ContainerDefinesResources)
- [ ] spec.template.spec.containers[1].resources.requests.memory not defined (ContainerDefinesResources)
- [ ] use of hostNetwork at spec.template.spec.hostNetwork not allowed (NoHostNetwork)
- [ ] use of hostPath at spec.template.spec.volumes[0].hostPath not allowed (NoHostPath)
- [ ] use of hostPath at spec.template.spec.volumes[1].hostPath not allowed (NoHostPath)
- [ ] use of hostPath at spec.template.spec.volumes[2].hostPath not allowed (NoHostPath)
- [ ] use of hostPath at spec.template.spec.volumes[3].hostPath not allowed (NoHostPath)
- [ ] use of hostPath at spec.template.spec.volumes[5].hostPath not allowed (NoHostPath)
- [ ] value "beta.kubernetes.io/arch" at some spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[i].matchExpressions[j].key not defined for architecture-based node affinity (PodHasArchBasedNodeAffinity)

**Comment by smitaraut** [comment] 2020-05-21 09:40
Is this still valid?

**Comment by mew2057** [comment] 2020-05-21 14:03
Technically yes, we still need a liveness probe and resource management, but apparently the rest were less of an issue.

**Comment by aspalazz** [comment] 2020-06-09 23:46
@mew2057 This is still set for CSI 2.0.0 - should we move it out?

**Comment by deeghuge** [comment] 2021-11-29 17:46
Duplicate of issue #467

**Closed by deeghuge** 2021-11-29 17:46 UTC
Labels: Component: Certification, Component: Templates, Environment: Kubernetes, Environment: OpenShift, Phase: Development, Severity: 2, Type: Bug, Type: Enhancement, Customer Probability: Can't Happen, Customer Impact: Minor
