### ISSUE TITLE
CSI driver creates directory instead of primary fileset

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-csi#454] opened 2021-08-04 22:00 UTC
**Describe the bug**
csi driver created directory `spectrum-scale-csi-volume-store` instead of fileset. It prevents CSI driver pods in running state,'

```
sh-4.4# mmlsfileset vdisknsd-sample -L
Filesets in file system 'vdisknsd-sample':
Name                            Id      RootInode  ParentId Created                      InodeSpace      MaxInodes    AllocInodes Comment
root                             0              3        -- Wed Aug  4 19:13:08 2021        0             12178944         503808 root fileset
sh-4.4# set -o vi
sh-4.4# find /mnt/vdisknsd-sample
/mnt/vdisknsd-sample
/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store
/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store/.volumes
/mnt/vdisknsd-sample/.snapshots
```

```
[root@c943f6n01-pvt ibm-spectrum-scale-container-native]# oc get pods
NAME                                                              READY   STATUS             RESTARTS   AGE
ibm-spectrum-scale-csi-5mm4g                                      3/3     Running            0          141m
ibm-spectrum-scale-csi-7zd82                                      2/3     CrashLoopBackOff   32         142m
ibm-spectrum-scale-csi-8kdnz                                      3/3     Running            0          142m
ibm-spectrum-scale-csi-attacher-0                                 1/1     Running            0          3h27m
ibm-spectrum-scale-csi-bnr2x                                      2/3     CrashLoopBackOff   32         142m
ibm-spectrum-scale-csi-cdcl8                                      2/3     CrashLoopBackOff   32         142m
ibm-spectrum-scale-csi-f8jjn                                      3/3     Running            0          142m
ibm-spectrum-scale-csi-fshqz                                      2/3     CrashLoopBackOff   32         142m
ibm-spectrum-scale-csi-pmrw5                                      3/3     Running            0          141m
ibm-spectrum-scale-csi-provisioner-0                              1/1     Running            0          3h27m
ibm-spectrum-scale-csi-r8nv6                                      3/3     Running            0          141m
ibm-spectrum-scale-csi-snapshotter-0                              1/1     Running            0          3h27m
ibm-spectrum-scale-csi-xgslz                                      3/3     Running            0          141m
ibm-spectrum-scale-ibm-spectrum-scale-csi-operator-fc98977n5l5r   1/1     Running            0          3h41m
[root@c943f6n01-pvt ibm-spectrum-scale-container-native]# oc l^C
[root@c943f6n01-pvt ibm-spectrum-scale-container-native]# k
-bash: k: command not found
[root@c943f6n01-pvt ibm-spectrum-scale-container-native]#
[root@c943f6n01-pvt ibm-spectrum-scale-container-native]# oc logs ibm-spectrum-scale-csi-cdcl8 -c ibm-spectrum-scale-csi
I0804 21:57:22.152100       1 gpfs.go:68] gpfs GetScaleDriver
I0804 21:57:22.152183       1 gpfs.go:145] gpfs SetupScaleDriver. name: spectrumscale.csi.ibm.com, version: 2.3.0, nodeID: worker1.ocp4-c1.pok.stglabs.ibm.com
I0804 21:57:22.152200       1 gpfs.go:183] gpfs PluginInitialize
I0804 21:57:22.152214       1 scale_config.go:93] scale_config LoadScaleConfigSettings
I0804 21:57:22.152494       1 scale_config.go:116] scale_config HandleSecrets
I0804 21:57:22.152563       1 gpfs.go:383] gpfs ValidateScaleConfigParameters.
I0804 21:57:22.152583       1 connectors.go:102] connector GetSpectrumScaleConnector
I0804 21:57:22.152591       1 rest_v2.go:120] rest_v2 NewSpectrumRestV2.
I0804 21:57:22.152602       1 rest_v2.go:142] Created Spectrum Scale connector without SSL mode for ibm-spectrum-scale-gui.ibm-spectrum-scale
I0804 21:57:22.152608       1 rest_v2.go:157] rest_v2 GetClusterId
I0804 21:57:22.152620       1 http_utils.go:60] http_utils FormatURL. url: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/
I0804 21:57:22.152634       1 rest_v2.go:839] rest_v2 doHTTP. endpoint: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/scalemgmt/v2/cluster, method: GET, param: <nil>
I0804 21:57:22.152641       1 http_utils.go:74] http_utils HttpExecuteUserAuth. type: GET, url: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/scalemgmt/v2/cluster, user: CsiAdmin
I0804 21:57:22.197104       1 http_utils.go:44] http_utils UnmarshalResponse. response: &{0x59fcc0 0xc0000cc040 0x6cf760}
I0804 21:57:22.197505       1 rest_v2.go:43] rest_v2 isStatusOK. statusCode: 200
I0804 21:57:22.197542       1 rest_v2.go:206] rest_v2 GetFilesystemMountDetails. filesystemName: vdisknsd-sample
I0804 21:57:22.197554       1 rest_v2.go:839] rest_v2 doHTTP. endpoint: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/scalemgmt/v2/filesystems/vdisknsd-sample, method: GET, param: <nil>
I0804 21:57:22.197562       1 http_utils.go:74] http_utils HttpExecuteUserAuth. type: GET, url: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/scalemgmt/v2/filesystems/vdisknsd-sample, user: CsiAdmin
I0804 21:57:22.211114       1 http_utils.go:44] http_utils UnmarshalResponse. response: &{0x59fcc0 0xc000220040 0x6cf760}
I0804 21:57:22.211545       1 rest_v2.go:43] rest_v2 isStatusOK. statusCode: 200
I0804 21:57:22.211569       1 rest_v2.go:225] rest_v2 IsFilesystemMountedOnGUINode. filesystemName: vdisknsd-sample
I0804 21:57:22.211578       1 http_utils.go:60] http_utils FormatURL. url: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/
I0804 21:57:22.211588       1 rest_v2.go:839] rest_v2 doHTTP. endpoint: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/scalemgmt/v2/filesystems/vdisknsd-sample, method: GET, param: <nil>
I0804 21:57:22.211605       1 http_utils.go:74] http_utils HttpExecuteUserAuth. type: GET, url: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/scalemgmt/v2/filesystems/vdisknsd-sample, user: CsiAdmin
I0804 21:57:22.221924       1 http_utils.go:44] http_utils UnmarshalResponse. response: &{0x59fcc0 0xc000117000 0x6cf760}
I0804 21:57:22.222112       1 rest_v2.go:43] rest_v2 isStatusOK. statusCode: 200
I0804 21:57:22.222143       1 rest_v2.go:237] filesystem [vdisknsd-sample] is [mounted] on GUI node
I0804 21:57:22.222153       1 gpfs.go:242] primaryFset is not specified in configuration using default spectrum-scale-csi-volume-store
I0804 21:57:22.222164       1 gpfs.go:325] gpfs CreatePrimaryFileset. primaryFS: vdisknsd-sample, mountpoint: /mnt/vdisknsd-sample, filesetName: spectrum-scale-csi-volume-store
I0804 21:57:22.222172       1 rest_v2.go:548] rest_v2 ListFileset. filesystem: vdisknsd-sample, fileset: spectrum-scale-csi-volume-store
I0804 21:57:22.222179       1 http_utils.go:60] http_utils FormatURL. url: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/
I0804 21:57:22.222190       1 rest_v2.go:839] rest_v2 doHTTP. endpoint: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/scalemgmt/v2/filesystems/vdisknsd-sample/filesets/spectrum-scale-csi-volume-store, method: GET, param: <nil>
I0804 21:57:22.222197       1 http_utils.go:74] http_utils HttpExecuteUserAuth. type: GET, url: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/scalemgmt/v2/filesystems/vdisknsd-sample/filesets/spectrum-scale-csi-volume-store, user: CsiAdmin
I0804 21:57:22.228203       1 http_utils.go:44] http_utils UnmarshalResponse. response: &{0x59fcc0 0xc0002200c0 0x6cf760}
I0804 21:57:22.228451       1 rest_v2.go:43] rest_v2 isStatusOK. statusCode: 400
E0804 21:57:22.228486       1 rest_v2.go:555] Error in list fileset request: Remote call completed with error [400 Bad Request]. Error in response [&{[] {400 Invalid value in 'filesetName'} {}}]
I0804 21:57:22.228500       1 gpfs.go:333] Primary fileset spectrum-scale-csi-volume-store not found. Creating it.
I0804 21:57:22.228508       1 rest_v2.go:390] rest_v2 CreateFileset. filesystem: vdisknsd-sample, fileset: spectrum-scale-csi-volume-store, opts: map[]
I0804 21:57:22.228520       1 http_utils.go:60] http_utils FormatURL. url: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/
I0804 21:57:22.228528       1 rest_v2.go:839] rest_v2 doHTTP. endpoint: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/scalemgmt/v2/filesystems/vdisknsd-sample/filesets, method: POST, param: {spectrum-scale-csi-volume-store    new    Fileset created by IBM Container Storage Interface driver          0 0 0 0 0 0  0 }
I0804 21:57:22.228544       1 http_utils.go:74] http_utils HttpExecuteUserAuth. type: POST, url: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/scalemgmt/v2/filesystems/vdisknsd-sample/filesets, user: CsiAdmin
I0804 21:57:22.272709       1 http_utils.go:44] http_utils UnmarshalResponse. response: &{0x59fcc0 0xc000396040 0x6cf760}
I0804 21:57:22.272970       1 rest_v2.go:43] rest_v2 isStatusOK. statusCode: 400
E0804 21:57:22.273028       1 rest_v2.go:437] Error in create fileset request: Remote call completed with error [400 Bad Request]. Error in response [&{{400 Input validation failed: EFSSG0762C The junction path "/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store" already exists.} []}]
E0804 21:57:22.273049       1 gpfs.go:341] Unable to create primary fileset spectrum-scale-csi-volume-store
E0804 21:57:22.273077       1 gpfs.go:289] Error in creating primary fileset
E0804 21:57:22.273085       1 gpfs.go:152] Error in plugin initialization: Remote call completed with error [400 Bad Request]. Error in response [&{{400 Input validation failed: EFSSG0762C The junction path "/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store" already exists.} []}]
F0804 21:57:22.273101       1 main.go:70] Failed to initialize Scale CSI Driver: Remote call completed with error [400 Bad Request]. Error in response [&{{400 Input validation failed: EFSSG0762C The junction path "/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store" already exists.} []}]
[root@c943f6n01-pvt ibm-spectrum-scale-container-nativ

```

**Comment by gandhisanjayv** [comment] 2021-08-04 22:03
manually recovered

```
[root@c943f6n01-pvt ibm-spectrum-scale-container-native]# oc rsh worker0
Defaulting container name to gpfs.
Use 'oc describe pod/worker0 -n ibm-spectrum-scale' to see all of the containers in this pod.
sh-4.4# set -o vi
sh-4.4# find /mnt/vdisknsd-sample
/mnt/vdisknsd-sample
/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store
/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store/.volumes
/mnt/vdisknsd-sample/.snapshots
sh-4.4# rm -rf /mnt/vdisknsd-sample/spectrum-scale-csi-volume-store
sh-4.4# find /mnt/vdisknsd-sample
/mnt/vdisknsd-sample
/mnt/vdisknsd-sample/.snapshots


root@c943f6n01-pvt ibm-spectrum-scale-container-native]# oc get pods
NAME                                                              READY   STATUS             RESTARTS   AGE
ibm-spectrum-scale-csi-5mm4g                                      3/3     Running            0          143m
ibm-spectrum-scale-csi-7zd82                                      2/3     CrashLoopBackOff   32         143m
ibm-spectrum-scale-csi-8kdnz                                      3/3     Running            0          143m
ibm-spectrum-scale-csi-attacher-0                                 1/1     Running            0          3h29m
ibm-spectrum-scale-csi-bnr2x                                      2/3     CrashLoopBackOff   32         143m
ibm-spectrum-scale-csi-cdcl8                                      2/3     CrashLoopBackOff   32         143m
ibm-spectrum-scale-csi-f8jjn                                      3/3     Running            0          143m
ibm-spectrum-scale-csi-fshqz                                      2/3     CrashLoopBackOff   32         143m
ibm-spectrum-scale-csi-pmrw5                                      3/3     Running            0          143m
ibm-spectrum-scale-csi-provisioner-0                              1/1     Running            0          3h29m
ibm-spectrum-scale-csi-r8nv6                                      3/3     Running            0          143m
ibm-spectrum-scale-csi-snapshotter-0                              1/1     Running            0          3h28m
ibm-spectrum-scale-csi-xgslz                                      3/3     Running            0          143m
ibm-spectrum-scale-ibm-spectrum-scale-csi-operator-fc98977n5l5r   1/1     Running            0          3h43m
[root@c943f6n01-pvt ibm-spectrum-scale-container-native]# oc delete pod ibm-spectrum-scale-csi-cdcl8
pod "ibm-spectrum-scale-csi-cdcl8" deleted
[root@c943f6n01-pvt ibm-spectrum-scale-container-native]# oc get pods
NAME                                                              READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-5mm4g                                      3/3     Running   0          145m
ibm-spectrum-scale-csi-7zd82                                      3/3     Running   33         145m
ibm-spectrum-scale-csi-8kdnz                                      3/3     Running   0          145m
ibm-spectrum-scale-csi-8m9br                                      3/3     Running   0          66s
ibm-spectrum-scale-csi-attacher-0                                 1/1     Running   0          3h30m
ibm-spectrum-scale-csi-bnr2x                                      3/3     Running   33         145m
ibm-spectrum-scale-csi-f8jjn                                      3/3     Running   0          145m
ibm-spectrum-scale-csi-fshqz                                      3/3     Running   33         145m
ibm-spectrum-scale-csi-pmrw5                                      3/3     Running   0          145m
ibm-spectrum-scale-csi-provisioner-0                              1/1     Running   0          3h30m
ibm-spectrum-scale-csi-r8nv6                                      3/3     Running   0          145m
ibm-spectrum-scale-csi-snapshotter-0                              1/1     Running   0          3h30m
ibm-spectrum-scale-csi-xgslz                                      3/3     Running   0          145m
ibm-spectrum-scale-ibm-spectrum-scale-csi-operator-fc98977n5l5r   1/1     Running   0          3h44m
[root@c943f6n01-pvt ibm-spectrum-scale-container-native]#

[root@c943f6n01-pvt ibm-spectrum-scale-container-native]# oc rsh worker0
Defaulting container name to gpfs.
Use 'oc describe pod/worker0 -n ibm-spectrum-scale' to see all of the containers in this pod.
sh-4.4# set -o vi
sh-4.4# find /mnt/vdisknsd-sample
/mnt/vdisknsd-sample
/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store
/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store/.volumes
/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store/.snapshots
/mnt/vdisknsd-sample/.snapshots
sh-4.4# mmlsfileset vdisknsd-sample -L
Filesets in file system 'vdisknsd-sample':
Name                            Id      RootInode  ParentId Created                      InodeSpace      MaxInodes    AllocInodes Comment
root                             0              3        -- Wed Aug  4 19:13:08 2021        0             12178944         503808 root fileset
spectrum-scale-csi-volume-store  1         524291         0 Wed Aug  4 22:01:37 2021        1              1048576          53248 Fileset created by IBM Container Storage Interface driver
sh-4.4#
```

**Comment by gandhisanjayv** [comment] 2021-08-20 22:48
hit issue again
```
I0820 22:40:48.254100       1 http_utils.go:44] http_utils UnmarshalResponse. response: &{0x59fcc0 0xc000200200 0x6cf760}
I0820 22:40:48.254360       1 rest_v2.go:43] rest_v2 isStatusOK. statusCode: 400
E0820 22:40:48.254393       1 rest_v2.go:555] Error in list fileset request: Remote call completed with error [400 Bad Request]. Error in response [&{[] {400 Invalid value in 'filesetName'} {}}]
I0820 22:40:48.254406       1 gpfs.go:333] Primary fileset spectrum-scale-csi-volume-store not found. Creating it.
I0820 22:40:48.254413       1 rest_v2.go:390] rest_v2 CreateFileset. filesystem: vdisknsd-sample, fileset: spectrum-scale-csi-volume-store, opts: map[]
I0820 22:40:48.254425       1 http_utils.go:60] http_utils FormatURL. url: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/
I0820 22:40:48.254435       1 rest_v2.go:839] rest_v2 doHTTP. endpoint: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/scalemgmt/v2/filesystems/vdisknsd-sample/filesets, method: POST, param: {spectrum-scale-csi-volume-store    new    Fileset created by IBM Container Storage Interface driver          0 0 0 0 0 0  0 }
I0820 22:40:48.254452       1 http_utils.go:74] http_utils HttpExecuteUserAuth. type: POST, url: https://ibm-spectrum-scale-gui.ibm-spectrum-scale:443/scalemgmt/v2/filesystems/vdisknsd-sample/filesets, user: CsiAdmin
I0820 22:40:48.301482       1 http_utils.go:44] http_utils UnmarshalResponse. response: &{0x59fcc0 0xc000200280 0x6cf760}
I0820 22:40:48.301705       1 rest_v2.go:43] rest_v2 isStatusOK. statusCode: 400
E0820 22:40:48.301779       1 rest_v2.go:437] Error in create fileset request: Remote call completed with error [400 Bad Request]. Error in response [&{{400 Input validation failed: EFSSG0762C The junction path "/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store" already exists.} []}]
E0820 22:40:48.301803       1 gpfs.go:341] Unable to create primary fileset spectrum-scale-csi-volume-store
E0820 22:40:48.301817       1 gpfs.go:289] Error in creating primary fileset
E0820 22:40:48.301824       1 gpfs.go:152] Error in plugin initialization: Remote call completed with error [400 Bad Request]. Error in response [&{{400 Input validation failed: EFSSG0762C The junction path "/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store" already exists.} []}]
F0820 22:40:48.301831       1 main.go:70] Failed to initialize Scale CSI Driver: Remote call completed with error [400 Bad Request]. Error in response [&{{400 Input validation failed: EFSSG0762C The junction path "/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store" already exists.} []}]
[root@c943f6n01-pvt generated]#
```

**Comment by gandhisanjayv** [comment] 2021-08-20 23:04
logs are under
/u/DUMPS/scale-core/csi-issue-454/

mount c5dump1.pok.stglabs.ibm.com:/DUMPS /u/DUMPS on your inf node of fyre.

**Comment by gandhisanjayv** [comment] 2021-08-20 23:12
tar -xvxf cnsalogcapture_2021-08-20-18.54.13.1629500053.tar.gz
cd cnsa_logs/
grep -ir mkdir *|more

```
s/ibm-spectrum-scale/gui/mgtsrv-system-log:2021-08-20T22:40:24 >AbstractCliCommand.logResult:263< INFO: CLI >>> Command "mkdirectory '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store/.volumes' '0:0' --cluster 5806857
289753175827 " executed by user "CsiAdmin@null(0)" completed with EXITCODE = 0 , STDERR =
ns/ibm-spectrum-scale/gui/mgtsrv-system-log:2021-08-20T22:40:24 >AbstractCliCommand.logResult:263< INFO: CLI >>> Command "mkdirectory '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store/.volumes' '0:0' --cluster 5806857
289753175827 " executed by user "CsiAdmin@null(0)" completed with EXITCODE = 0 , STDERR =
ns/ibm-spectrum-scale/gui/mgtsrv-system-log:2021-08-20T22:40:25 >AbstractCliCommand.logResult:263< INFO: CLI >>> Command "mkdirectory '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store/.volumes' '0:0' --cluster 5806857
289753175827 " executed by user "CsiAdmin@null(0)" completed with EXITCODE = 0 , STDERR =
ns/ibm-spectrum-scale/gui/mgtsrv-trace-log:2021-08-20T22:40:22 >AbstractCliCommand.logEntrance:256//scalemgmt/v2/filesystems/vdisknsd-sample/directory/spectrum-scale-csi-volume-store%2F.volumes/CsiAdmin/0< INFO: CLI >>> C
ommand "mkdirectory '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store/.volumes' '0:0' --cluster 5806857289753175827 " issued by user "CsiAdmin@null(0)"
ns/ibm-spectrum-scale/gui/mgtsrv-trace-log:2021-08-20T22:40:22 >AbstractCommand.buildOsCommandWrapper:195< FINER: making call to mkdir -p '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store'
ns/ibm-spectrum-scale/gui/mgtsrv-trace-log:2021-08-20T22:40:22 >OsCommandWrapper.execute:268< FINER: EFSSA0037I Command mkdir -p '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store'  was issued on host localhost by user
 R:CsiAdmin.
ns/ibm-spectrum-scale/gui/mgtsrv-trace-log:2021-08-20T22:40:22 >OsCommandWrapper.execute:292< FINER: Command mkdir -p '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store'  finished with exit code 0
ns/ibm-spectrum-scale/gui/mgtsrv-trace-log:2021-08-20T22:40:23 >AbstractCliCommand.logEntrance:256//scalemgmt/v2/filesystems/vdisknsd-sample/directory/spectrum-scale-csi-volume-store%2F.volumes/CsiAdmin/0< INFO: CLI >>> C
ommand "mkdirectory '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store/.volumes' '0:0' --cluster 5806857289753175827 " issued by user "CsiAdmin@null(0)"
ns/ibm-spectrum-scale/gui/mgtsrv-trace-log:2021-08-20T22:40:23 >AbstractCliCommand.logEntrance:256//scalemgmt/v2/filesystems/vdisknsd-sample/directory/spectrum-scale-csi-volume-store%2F.volumes/CsiAdmin/0< INFO: CLI >>> C
[root@c943f6n01-pvt cnsa_logs]# ^Cr -xvxf cnsalogcapture_2021-08-20-18.54.13.1629500053.tar.gz
[root@c943f6n01-pvt cnsa_logs]# #grep -ir mkdir *|more
```

```ns/ibm-spectrum-scale/gui/mgtsrv-trace-log:2021-08-20T22:40:22 >AbstractCliCommand.logEntrance:256//scalemgmt/v2/filesystems/vdisknsd-sample/directory/spectrum-scale-csi-volume-store%2F.volumes/CsiAdmin/0< INFO: CLI >>> C
ommand "mkdirectory '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store/.volumes' '0:0' --cluster 5806857289753175827 " issued by user "CsiAdmin@null(0)"
ns/ibm-spectrum-scale/gui/mgtsrv-trace-log:2021-08-20T22:40:22 >AbstractCommand.buildOsCommandWrapper:195< FINER: making call to mkdir -p '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store'
ns/ibm-spectrum-scale/gui/mgtsrv-trace-log:2021-08-20T22:40:22 >OsCommandWrapper.execute:268< FINER: EFSSA0037I Command mkdir -p '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store'  was issued on host localhost by user
 R:CsiAdmin.
ns/ibm-spectrum-scale/gui/mgtsrv-trace-log:2021-08-20T22:40:22 >OsCommandWrapper.execute:292< FINER: Command mkdir -p '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store'  finished with exit code 0
ns/ibm-spectrum-scale/gui/mgtsrv-trace-log:2021-08-20T22:40:23 >AbstractCliCommand.logEntrance:256//scalemgmt/v2/filesystems/vdisknsd-sample/directory/spectrum-scale-csi-volume-store%2F.volumes/CsiAdmin/0< INFO: CLI >>> C
ommand "mkdirectory '/mnt/vdisknsd-sample/spectrum-scale-csi-volume-store/.volumes' '0:0' --cluster 5806857289753175827 " issued by user "CsiAdmin@null(0)"
ns/ibm-spectrum-scale/gui/mgtsrv-trace-log:2021-08-20T22:40:23 >AbstractCliCommand.logEntrance:256//scalemgmt/v2/filesystems/vdisknsd-sample/directory/spectrum-scale-csi-volume-store%2F.volumes/CsiAdmin/0< INFO: CLI >>> C
```

**Comment by Sunil-Kumar20** [comment] 2021-08-25 09:06
I am not able to recreate the issue on my local dev environment. 
@gandhisanjayv  please help to replicate the issue over dev environment.

**Comment by Jainbrt** [comment] 2022-03-11 08:05
@Sunil-Kumar20 do we have any update on this issue ?

**Comment by Sunil-Kumar20** [comment] 2022-03-11 08:31
HI @Jainbrt 
Currently unable to reproduce the issue do we have any setup where it is reoccurring or reproducible ?

**Comment by deeghuge** [comment] 2022-03-11 14:04
Hi @Sunil-Kumar20 , I do have setup where issue is recreated.

**Comment by Sunil-Kumar20** [comment] 2022-03-11 16:19
HI 
While debugging it is found as CSI Sending multiple requests to both the GUI to create the fileseSet and one of them will succeed and rest will fail but currently if pod A receives the request for creating a file set and pod B also in parallel, in that case one will succeed and other will return a command failed exception and as per implementation will perform revert back operation in that case it deletes the file set.
```
2022-03-11T11:25:14 >OsCommandWrapper.execute:292< FINER: Command mmcrfileset 'fs1' 'primary-fileset-fs1-8974681616608340152' -t 'Fileset created by IBM Container Storage Interface driver' --inode-space new --inode-limit '1M:50K' --allow-permission-change 'chmodAndSetAcl'  finished with exit code 17
2022-03-11T11:25:14 >CmdMkFSet.doExecute:283//scalemgmt/v2/filesystems/fs1/filesets/CsiAdmin/0< SEVERE: The fileset primary-fileset-fs1-8974681616608340152 cannot be created. Cause: Fileset primary-fileset-fs1-8974681616608340152 already exists.
mmcrfileset: Command failed. Examine previous error messages to determine cause.
.
2022-03-11T11:25:14 >CommandException.createCommandException:54< FINE: com.ibm.fscc.cli.CommandException: EFSSG1072C The fileset primary-fileset-fs1-8974681616608340152 cannot be created. Cause: Fileset primary-fileset-fs1-8974681616608340152 already exists.
mmcrfileset: Command failed. Examine previous error messages to determine cause.
.
	at com.ibm.fscc.cli.CommandException.createCommandException(CommandException.java:121)
	at com.ibm.fscc.newcli.commands.fileset.CmdMkFSet.doExecute(CmdMkFSet.java:285)
	at com.ibm.fscc.newcli.internal.AbstractCliCommand.execute(AbstractCliCommand.java:156)
	at com.ibm.fscc.rest.async.AsyncJobRegistry.lambda$submitJob$0(AsyncJobRegistry.java:95)
	at <unknown class>.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:866)

2022-03-11T11:25:14 >AbstractCliCommand.logResult:263//scalemgmt/v2/filesystems/fs1/filesets/CsiAdmin/0< INFO: CLI >>> Command "mkfset fs1 'primary-fileset-fs1-8974681616608340152' --comment 'Fileset created by IBM Container Storage Interface driver' --independent -i '1M:50K' --junction '/mnt/fs1/primary-fileset-fs1-8974681616608340152' --allowPermissionChange chmodAndSetAcl --cluster 8974681616608340152 " executed by user "CsiAdmin@null(0)" completed with EXITCODE = 8 , STDERR = EFSSG1072C The fileset primary-fileset-fs1-8974681616608340152 cannot be created. Cause: Fileset primary-fileset-fs1-8974681616608340152 already exists.
mmcrfileset: Command failed. Examine previous error messages to determine cause.
.
2022-03-11T11:25:14 >AbstractCommand.buildOsCommandWrapper:195< FINER: making call to mmlsfileset 'fs1' 'primary-fileset-fs1-8974681616608340152' -Y 
2022-03-11T11:25:14 >OsCommandWrapper.execute:268< FINER: EFSSA0037I Command mmlsfileset 'fs1' 'primary-fileset-fs1-8974681616608340152' -Y  was issued on host localhost by user R:CsiAdmin.
2022-03-11T11:25:15 >OsCommandWrapper.execute:292< FINER: Command mmlsfileset 'fs1' 'primary-fileset-fs1-8974681616608340152' -Y  finished with exit code 0
2022-03-11T11:25:15 >AbstractCommand.buildOsCommandWrapper:195< FINER: making call to mmunlinkfileset 'fs1' 'primary-fileset-fs1-8974681616608340152' -f 
2022-03-11T11:25:15 >OsCommandWrapper.execute:268< FINER: EFSSA0037I Command mmunlinkfileset 'fs1' 'primary-fileset-fs1-8974681616608340152' -f  was issued on host localhost by user R:CsiAdmin.
2022-03-11T11:25:15 >AbstractCommand.buildOsCommandWrapper:195< FINER: making call to /usr/lpp/mmfs/gui/bin-sudo/tsstatus.sh 
2022-03-11T11:25:15 >OsCommandWrapper.execute:268< FINER: EFSSA0037I Command /usr/lpp/mmfs/gui/bin-sudo/tsstatus.sh  was issued on host localhost by user G:unknown.
2022-03-11T11:25:15 >OsCommandWrapper.execute:292< FINER: Command /usr/lpp/mmfs/gui/bin-sudo/tsstatus.sh  finished with exit code 1
2022-03-11T11:25:15 >AbstractCommand.buildOsCommandWrapper:195< FINER: making call to mmlsfileset 'fs1' -Y 
2022-03-11T11:25:15 >OsCommandWrapper.execute:268< FINER: EFSSA0037I Command mmlsfileset 'fs1' -Y  was issued on host localhost by user G:unknown.
2022-03-11T11:25:15 >OsCommandWrapper.execute:292< FINER: Command mmunlinkfileset 'fs1' 'primary-fileset-fs1-8974681616608340152' -f  finished with exit code 0
2022-03-11T11:25:15 >AbstractCommand.buildOsCommandWrapper:195< FINER: making call to mmdelfileset 'fs1' 'primary-fileset-fs1-8974681616608340152' -f --qos 'maintenance' 
2022-03-11T11:25:15 >OsCommandWrapper.execute:268< FINER: EFSSA0037I Command mmdelfileset 'fs1' 'primary-fileset-fs1-8974681616608340152' -f --qos 'maintenance'  was issued on host localhost by user R:CsiAdmin.
2022-03-11T11:25:16 >OsCommandWrapper.execute:292< FINER: Command mmlsfileset 'fs1' -Y  finished with exit code 0

```

**Comment by Sunil-Kumar20** [comment] 2022-04-25 07:25
Fix has been delivered under below RTC
https://jazz07.rchland.ibm.com:21443/jazz/web/projects/GPFS#action=com.ibm.team.workitem.viewWorkItem&id=280403

**Comment by gandhisanjayv** [comment] 2022-04-29 06:22
This is hard to recreate this defect. So difficult to verify. we see it while deploying ECE filesystem.

**Comment by Jainbrt** [comment] 2022-05-26 10:30
we can close this defect for now, as this is not recreating on new CNSA builds. Request to open a new defect if we see similar problem again

**Closed by Jainbrt** 2022-05-26 10:30 UTC
Labels: Severity: 2, Type: Bug, Customer Probability: Low, Customer Impact: Global, Type: Needs Verification by Originator
