### ISSUE TITLE
Should adhere to cloudpak operator status guidelines 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#678] opened 2022-03-12 11:24 UTC
## Describe the bug
Should adhere to cloudpak operator status guidelines 

## How to Reproduce?
Check the operator status 

## Expected behavior
Details on : https://playbook.cloudpaklab.ibm.com/cm/opstatus
```
    General
        Status MUST be modeled as a subresource.
        The health of an operand MUST be easily determined by using the status.
        Status MUST be documented as part of the resource API.
        The status section MUST NOT Include any sensitive information.
        OLM statusDescriptors (in the CSV) SHOULD be used for status items that you want to surface in the OpenShift UI.
        spec.additionalPrinterColumns (in the CRD) SHOULD be used to report additional status for CLI (kubectl/oc) users.

    Conditions
        Conditions useful for other components or the user MUST be documented as part of the resource API.
        Conditions MUST be used to indicate the health of an operand. Report status using status.conditions.
        Conditions MUST include a reason, message, and lastTransitionTime to inform users on what actions, if any, are needed.
        Operators SHOULD leverage the following core conditions: Progressing, Available, Degraded, and Upgradeable when applicable.
    Endpoints
        You MUST include important endpoints/URLs in your status.
        Any included endpoint information SHOULD be reported using a endpoints[] array in your status section.
    Versions
        The version of the Operator and/or Operand(s) MUST be reported in your status.
        During an upgrade you MUST report the previous operator/operand version until you can guarantee you will not run any old versions of your operand(s).
        Operator or Operand versions SHOULD be reported using a status.versions[] array, where each element is a [name, version] tuple.
        Fan-out operators SHOULD report the available "versions" or "channels" to which the operand my be upgraded/rolled back to in their status.


Notes:

    Ansible/Helm Operators are limited in their ability to support certain status requirements (exceptions will be allowed in those cases).
```

**Comment by deeghuge** [comment] 2022-06-30 04:43
Duplicate of #457

**Closed** 2022-09-09 12:46 UTC
Labels: Severity: 3, Type: Bug, Customer Probability: High, Customer Impact: Localized low impact, cloudpak-certification-requirement
